"""empty message

Revision ID: 263d30bc54cd
Revises: 2ab3109ea19d
Create Date: 2020-04-04 23:49:09.728342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263d30bc54cd'
down_revision = '2ab3109ea19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###\


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
